#!/bin/bash

main() {
	echo "This demo application is extensible with plugins."
	echo
	echo "Here are the plugins currently available:"
	./plugn list
	echo
	echo "You can enable plugins with:"
	echo '  $ plugn enable <plugin>'
	echo
	./plugn enable example-plugin1 example-plugin2
	echo
	echo "Now, on to the demo. What is your name?"
	read name
	echo
	echo "Okay, I'm going to greet you, but by using the plugins."
	echo "I'm doing this by triggering a hookA script in each plugin."
	echo
	./plugn trigger hookA $name
}

main "$@"